In [8]:
import numpy as np 
from numpy import random
x=random.randint(100)
y=random.normal(loc=2,scale=4, size=(2,3))
print(x)
print(y)

89
[[-1.9011762  10.66335816  2.23551517]
 [ 5.41248521 -1.74779138 -2.84490517]]


In [10]:
x=random.binomial(n=10,p=0.5,size=10)
print(x)

[6 3 5 6 7 7 3 5 5 5]
