In [5]:
import numpy as np
a=[i for i in range(41)]
array=np.array(a)
print(a)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
    arr1 = np.array([1, 2, 3])
    arr2 = np.append(arr1, ["HIIiiiiiiii", "NOOOOOOOOOOOOOOOO"])
    print(arr2)

['1' '2' '3' 'HIIiiiiiiii' 'NOOOOOOOOOOOOOOOO']


In [25]:
print((np.array(10)).ndim)
print((np.array([1,1,1,1])).ndim)
print((np.array([[1,1,1,1],[2,2,2]])).ndim)
d=(np.array(([[1,1,1,1],[2,2,2],[3,3,3],[4,4,4]])))
print(d)

0
1


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [32]:
a=np.array([1,2,3,4,5,6])
print(a[2:5])

[3 4 5]


In [40]:
ary=np.array([1,2,3,4,5,6])
print("original ",ary)
copy=np.empty_like(a)
copy=ary
print("copy ",copy)

original  [1 2 3 4 5 6]
copy  [1 2 3 4 5 6]


In [42]:
ary=np.array([1.54,2.56,3.34,4.567,5.67,6.754])
print("original ",ary)
copy=np.copy(a)
copy=ary
print("copy ",copy)

original  [1.54  2.56  3.34  4.567 5.67  6.754]
copy  [1.54  2.56  3.34  4.567 5.67  6.754]


In [46]:
a=np.arange(1,6)
for i in a:
    print(i)

1
2
3
4
5


In [48]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("original:  ",a)
a[0,3]=300
print("assign op:  ",a)

original:   [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
assign op:   [[  1   2   3 300   5   6   7]
 [  8   9  10  11  12  13  14]]


In [51]:
arr=np.array([[["h","i"],["h","l"]],[["h","i"],["h","l"]]])
for i in np.nditer(arr):
    print(i)

h
i
h
l
h
i
h
l


In [55]:
z=np.identity(1)
print(z)

[[1.]]


In [56]:
n=np.array([[1,2,3,3,4],[1,2,3,4,4]])
print(n)

[[1 2 3 3 4]
 [1 2 3 4 4]]


In [63]:
n.reshape(5,2)

array([[1, 2],
       [3, 3],
       [4, 1],
       [2, 3],
       [4, 4]])

+

+n=np.array([1,2,3,3,4,1,2,3,4,4,1,2])
n.reshape(2,2,3)

In [79]:
n=np.array([[1,2,4],[10,20,30],[100,200,300]])
print(n.max(axis=1))
print(n.max(axis=0))
print(n.min(axis=0))
print(n.min(axis=1))
print(n.sum())

[  4  30 300]
[100 200 300]
[1 2 4]
[  1  10 100]
667
