In [102]:
import numpy as np

In [103]:
a=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [104]:
b=np.array([[1,2,3],[3,1,0]])
print(b)

[[1 2 3]
 [3 1 0]]


In [105]:
#print(a*b)

In [106]:
#number of rows
a.ndim

2

In [107]:
#number of rows and columns
b.shape

(2, 3)

In [108]:
#type to change type add argument to declaration "dtype=int16"
a.dtype

dtype('int64')

In [109]:
#number of bytes taken by single element
a.itemsize

8

In [110]:
#size tells you how many elements are present in the entire array.

a.size

30

In [111]:
#total size of all element
a.nbytes

240

In [112]:
#calc
print(a.itemsize*a.size)

240


In [113]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [114]:
#[row, starting:ending:skip]
print(a[1, : :-2])

[10  8  6  4  2]


In [115]:
#works for columns same way
print(a[ 1: 2:,5])

[6]


In [116]:
a[1,::-2]=1
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  1  3  1  5  1  7  1  9  1]
 [ 1  2  3  4  5  6  7  8  9 10]]
